### ISSUE TITLE
Update session - Teaching IT Pro how to Dev

### ISSUE THREAD

**Issue by kilasuit** [kilasuit/Presentations#1]
I will be presenting a new version of this session which for reference is at https://github.com/kilasuit/Presentations/blob/master/Teaching%20The%20It%20Pro%20How%20to%20Dev/Teaching%20the%20ITPro%20how%20to%20Dev.pptx

Due to this I am looking for any pointers for items that could be of use to include.

Examples that I will investigate further to add into this new session, which is mainly focused towards IT Pros that may be starting out or expanding their scripting skills and predominantly using PowerShell in this journey, a few example that I can think of would include

- PowerShell Modules `PoshGit`
- VSCode Extensions  `BracketColoriser, GitLens, VSTS/AzureDevOps `
- Pester Examples `DBAChecks is a good example of this`
- DSC Examples `SharePointDSC`
- Blogs to follow 
- People to follow
- Communities to join

Thanks in advance to anyone that comments and I will add notes in the session that you contributed ideas and thoughts in this `Community Sourced Thoughts to Updated Presentation Development`

**Comment by kilasuit** [comment]
I will note this is not just to be VSCode or PowerShell modules specific but should ideally be focused around

If there are other tools that are useful and have write ups that I can review and can be easily then please feel free to mention them.

**Comment by shaneis** [comment]
Given that I just spent around 40 minutes last night writing and commenting out lines for debugging before I actually ran the debugger in VSCode, how about something on using the debugger? 😄

**Comment by kilasuit** [comment]
Things to add

- [ ] Git Commit hooks - Jason Browns Blog
- [ ] PowerShell Modules that I use / been recommended
- [ ] Posh-Git
- [ ] PowerShell Gallery / PowerShell Get
- [ ] GitHub links
- [ ] Slack - Worldwide and UK
- [ ] Meetup Groups
- [ ] Twitter list from Brett & my FF tweet
- [ ] YouTube Links
- [ ] Powershell.org
- [ ] Conferences

https://app.pluralsight.com/player?course=debugging-powershell-vs-code&author=josh-duffney&name=1694b075-5675-4724-aa76-9441e4bb3158&clip=2&mode=live

**Comment by kilasuit** [comment]
- [ ] PSKoans - thanks to @vexx32
- [ ] EditorServicesCommandSuite  - @seeminglyscience
- [ ] Better Creds -  @jaykul and reccomendation from 



Blogs 
- [ ] https://kevinmarquette.github.io/
- [ ] PowerShell Planet

**Comment by kilasuit** [comment]
Closing due to commit https://github.com/kilasuit/Presentations/commit/c78735c6e92b1ead92b3eb4bcaaa1faf2869474e
